Дз №3
a-shchupakov/liquid-log pull request #2
Opened 2018-10-15 20:17 UTC by a-shchupakov

Щупаков Антон, КН-301

2018-10-15 21:04 UTC, a-shchupakov commented
Пока что убрал класс DataSet, потому что в данный момент содержимое DataSet определялось выбранным режимом (sdng, gc, top)
То есть, выбрав режим sdng мы наперед знаем, что не будут заполняться ни top, ни gc статистики

2018-10-16 17:43 UTC, ykalemi requested changes
Направление в целом правильное.
Но есть проблема с TopParser. И в некоторых случаях код не стал лучше.

Важно, чтобы TopParser снова заработал

2018-10-16 17:43 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +import javax.inject.Inject;
на будущее: лучше убирать такие файлы из коммитов, а различное форматирование, переименования, исправление опечаток - убирать в отдельные коммиты, чтобы не усложнять ревью кода

2018-10-16 17:43 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/InfluxDAO.java
> +        if (dataStorage instanceof SdngDataStorage) {
В этом методе теперь стало слишком много if-ов - это свидетельствует о плохой архитектуре. Такой код будет сложно расширять, т.е. добавлять новый парсер будет тяжело

2018-10-16 17:43 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            ITimeParser sdngTimeParser = new SdngTimeParser();
давайте здесь пойдем чуть дальше - у вас внутри каждого case код отличается только созданием парсеров. Надо только это и оставить, весь остальной код вынести за пределы switch и сделать общим

2018-10-16 17:43 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +                if (timeParser instanceof GCTimeParser)
здесь тоже стало немного хуже из-за обилия if-ов

2018-10-16 17:43 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parsers/time/TopTimeParser.java
> +        long time = 0;
У вас с TopParser есть проблема - он теперь не работает. Подробнее было в телеграм канале

2018-10-27 09:37 UTC, a-shchupakov commented
@ykalemi
Починил TopParser, убрал полотно if-ов

2018-10-29 07:50 UTC, ykalemi approved these changes
Ок.
На будущее - баги лучше покрывать тестами (вообще, лучше писать тесты изначально).

2018-10-29 11:59 UTC, merged