ДЗ №4
a-shchupakov/liquid-log pull request #3
Opened 2018-10-28 11:47 UTC by a-shchupakov

@d0k1
@ykalemi

2018-10-28 11:52 UTC, a-shchupakov commented
Только последние два коммита относятся к этому заданию

2018-10-29 10:24 UTC, d0k1 requested changes

2018-10-29 10:24 UTC, d0k1 commented on src/main/java/ru/naumen/perfhouse/influx/IDataBase.java
> +    void init();
нельзя ли отказаться от init и делать инициализацию в конструкторе?

2018-10-29 10:24 UTC, d0k1 commented on src/main/java/ru/naumen/sd40/log/parser/InfluxDAOWorker.java
> +    public void init() {
но ведь есть конструктор, как раз для инициализации

2018-10-29 12:21 UTC, a-shchupakov commented on src/main/java/ru/naumen/perfhouse/influx/IDataBase.java
> +    void init();
Можно, но я не хотел сильно нагружать конструктор
Там происходит подключение к бд и еще запрос к ней, слишком много работы получается для конструктора. Ведь при его вызове (конструктора) ожидается получить объект и не делать сложных манипуляций внутри

2018-10-29 13:39 UTC, d0k1 approved these changes
задание принято

2018-10-29 17:08 UTC, merged