Issue 10
a-shchupakov/liquid-log pull request #8
Opened 2018-11-29 16:08 UTC by a-shchupakov

2018-11-29 16:35 UTC, a-shchupakov commented
@d0k1
@ykalemi

2018-11-29 17:35 UTC, ykalemi requested changes
в целом все ок, небольшой фикс нужен

2018-11-29 17:35 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/parseMods/ParseMode.java
> +@Component
Component на интерфейсе?

2018-11-29 17:35 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/LogParser.java
> +    public LogParser(Map<String, ParseMode> parseModes) {
👍

2018-11-29 19:19 UTC, a-shchupakov commented
Поправил.
Почему-то думал, что это необходимо для того, чтобы внедрить все Bean'ы, которые реализуют данный интерфейс

2018-11-30 02:33 UTC, ykalemi approved these changes

2018-11-30 02:35 UTC, merged